menu:
  Home:
  Archives: archives
  Wishlist: wishlist
#  Chronicles: chronicles
#  Donate: donate
  Subscribe: atom.xml

widgets:
- search
- category
- tagcloud
- recent_posts

excerpt_link: Читать дальше

twitter:
  username:
  show_replies: false
  tweet_count: 5
  enable: false

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:

comment_provider: false
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
